kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wiki-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: premium-rwo
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-replica-io
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: premium-rwo
